#!/usr/bin/env node

/**
 * E2E Development Server Script
 *
 * This script ensures that the E2E test environment uses .env.test
 * and prevents accidental use of production database.
 */

import fs from "fs";
import path from "path";
import { spawn } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, "..");
const envTestPath = path.join(rootDir, ".env.test");
const envLocalPath = path.join(rootDir, ".env.local");

// ANSI color codes
const RED = "\x1b[31m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RESET = "\x1b[0m";

console.log(`${GREEN}=== E2E Development Server ===${RESET}\n`);

// Check if .env.test exists
if (!fs.existsSync(envTestPath)) {
  console.error(`${RED}❌ ERROR: .env.test file not found!${RESET}`);
  console.error(`   Expected location: ${envTestPath}`);
  console.error(`   Please create .env.test with local Supabase configuration.\n`);
  process.exit(1);
}

// Read .env.test content
const envTestContent = fs.readFileSync(envTestPath, "utf-8");

// SAFETY CHECK: Verify .env.test doesn't contain production URL
if (envTestContent.includes("uiyurwyzsckkkoqthxmv.supabase.co")) {
  console.error(`${RED}❌ CRITICAL ERROR: .env.test contains PRODUCTION database URL!${RESET}`);
  console.error(`   File: ${envTestPath}`);
  console.error(`   Found: uiyurwyzsckkkoqthxmv.supabase.co`);
  console.error(`   Expected: http://127.0.0.1:54321 (local Supabase)`);
  console.error(`\n   E2E tests MUST NOT run against production!`);
  console.error(`   Please update .env.test to use local Supabase.\n`);
  process.exit(1);
}

// SAFETY CHECK: Verify it contains local URL
if (!envTestContent.includes("127.0.0.1:54321") && !envTestContent.includes("localhost:54321")) {
  console.error(`${YELLOW}⚠️  WARNING: .env.test might not be configured for local Supabase${RESET}`);
  console.error(`   Expected to find: 127.0.0.1:54321 or localhost:54321`);
  console.error(`   Please verify your .env.test configuration.\n`);
}

console.log(`${GREEN}✅ Safety Check Passed:${RESET} .env.test is using local Supabase`);
console.log(`${GREEN}✅ Environment:${RESET} E2E test mode\n`);

// Create .env.local from .env.test (Astro prioritizes .env.local)
console.log(`${YELLOW}📝 Creating temporary .env.local from .env.test...${RESET}`);
fs.writeFileSync(
  envLocalPath,
  `# AUTO-GENERATED by scripts/dev-e2e.js - DO NOT EDIT\n` +
    `# This file is created from .env.test for E2E testing\n` +
    `# It will be automatically deleted when the server stops\n\n` +
    envTestContent
);

console.log(`${GREEN}✅ Temporary .env.local created${RESET}\n`);
console.log(`${GREEN}🚀 Starting Astro development server...${RESET}\n`);

// Start Astro dev server
const astroProcess = spawn("npm", ["run", "dev"], {
  stdio: "inherit",
  shell: true,
  cwd: rootDir,
});

// Cleanup function
const cleanup = () => {
  console.log(`\n\n${YELLOW}🧹 Cleaning up temporary .env.local...${RESET}`);
  if (fs.existsSync(envLocalPath)) {
    fs.unlinkSync(envLocalPath);
    console.log(`${GREEN}✅ Temporary .env.local removed${RESET}\n`);
  }
  process.exit(0);
};

// Handle cleanup on exit
process.on("SIGINT", cleanup);
process.on("SIGTERM", cleanup);
process.on("exit", cleanup);

// Handle Astro process exit
astroProcess.on("exit", (code) => {
  cleanup();
  process.exit(code || 0);
});
